### ISSUE TITLE
Shortcuts: Incorrect Burst command in Monstrosity

### ISSUE THREAD

**Issue by Grouf** [Byrth/Lua-Byrth#373]
When I am playing as a Scolopendrid and I attempt to cast Burst, either from the menu or command line, shortcuts changes the command to `/ms "Burst" 17252669`.

I unloaded all add-ons and burst worked, then loaded only shortcuts and it changed to the wrong command.  This is the only spell I've seen that shortcuts will make incorrect.

Not a big issue, I'll unload shorcuts, but I thought I'd let you know in case it's more then monstrosity.

**Comment by Byrth** [comment]
Shortcuts is generally broken in Monstrosity at the moment (although it probably still works for most magic) because the monstrosity resources are broken. Arcon is probably going to fix them some day, but given SE's lack of support for Monstrosity it's not a high priority issue.

The two issues with it are here:
https://github.com/Windower/ResourceExtractor/issues

Because it doesn't really have anything to do with shortcuts, I'm going to close this issue. Thanks for the report, though!
