### ISSUE TITLE
Lua runtime error/gearswap.lua:367 a nil value

### ISSUE THREAD

**Issue by Ballanoir** [Byrth/Lua-Byrth#382]
Each time an item is traded or dropped to my inventory i get this error:

lua runtime error: D/windower4//addons/gearswap/gearswap.lua:367: attempt to index field '?' (a nil value)

if anyone can help me fix this 

this error happend after may update

**Comment by thecuriousorange** [comment]
was going to start a new issue, but this seems to be part of the same issue.

"lua runtime error GearSwap/GearSwap.lua:364: attempt to index field '?' (a nil value)" occurs when I disengage.

"lua runtime error GearSwap/GearSwap.lua:382: attempt to index field '?' (a nil value)" occurs when I open /bank2 aka mog safe 2.

382 also pops up when I talk to a waypoint, it might pop up when I start to interact with an npc of any kind.

382 just popped up after running in north sandy as well, maybe because that's when my inventory loaded.

additionally when taking items from my delivery box I get "lua runtime error GearSwap/GearSwap.lua:367: attempt to index field '?' (a nil value)

**Comment by Nezkeys** [comment]
I'm getting this problem with all the same things as you mentioned. The lines in question on the gearswap haven't been edited either and look fine

**Comment by jllove** [comment]
Hi all,
I've been receiving the same messages on my BG Console whenever I zone into a new area, trade items, casting spells, etc. The messgae is:

When changing zones and trading
Gearswap: Lua runtime error: gearswap/gearswap.lua:384: attempt to index field '?' (a nil value)

When trading
Gearswap: Lua runtime error: gearswap/gearswap.lua:367: attempt to index field '?' (a nil value)

When casting spells to change gear
Gearswap: Lua runtime error: gearswap/equip_processing.lua:288 attempt to index field '?' (a nil value)

**Comment by Ballanoir** [comment]
Looks like the errors come from the new mogsafe2 idk how to fix it yet tho

**Comment by Byrth** [comment]
Yes, this was due to the expansion of mogsafe2 and Rooks fixed it. I just pushed a change to -dev that should keep it fixed in the future even if they give us more bags.

Thanks for the reports!
