### ISSUE TITLE
Pointwatch error

### ISSUE THREAD

**Issue by Kigenkotsu** [Byrth/Lua-Byrth#383]
PointWatch: Lua runtime error: pointwatch/pointwatch.lua:109: attempt to index a nil value
only effects my main character, all others no problem. Any info or help fixing this would be great thanks. Side note: TParty and distance loose display also. All settings work fine upon logon or (while in game) zone from one area to another then remove 6-8 sec after. If i zone again they do appear agian briefly.

**Comment by Byrth** [comment]
This indicates that windower.ffxi.get_player() is returning nil. I recently created an issue for someone with a similar problem:
https://github.com/Windower/Issues/issues/732

As this problem is outside the scope of GearSwap (and actually I assume it has already been fixed), I'm going to close this issue. If you continue having problems, please post in the linked thread.
