### ISSUE TITLE
Future of State values.

### ISSUE THREAD

**Issue by Badurkadur1** [Byrth/Lua-Byrth#450]
I've poked around GearSwap quite a bit over the years, though I am no coder by any means.  I have a question pertaining to Motenten's old Global files, and possibly a way around them.  I know for many,  Mote globals are not preferred due to being somewhat specific, and restrictive in some scenarios, but it did offer the ability of making "States" with which you can make more complex arguments more easily.

What I was wondering is, exactly how does making a state work?  How could a new global be made that allows the use of states in daughter files, without having to just use all of Mote-Globals?

I mostly want to know this for things like the BLU lua, which is unable to incorporate auto-movement speed, due to it relying on state values.  It also makes for much simpler handling of enabling and disabling certain functions completely based on certain parameters (i.e. buffs switching certain states on and off) and I think there would be alot the community has to gain by being able to implement these without using Motenten based globals.  

Sorry in advance if you've had to answer this question before.

**Comment by Byrth** [comment]
I am unfamiliar with the Motenten's idea of "States" and cannot really answer your question.

If you look at my gearswap files (included in the distribution), you will see that I handle things like movement speed gear with self_command toggles.

Going to close this because it seems like a user file issue rather than a gearswap API issue.
